name: 継続的インテグレーション

on:
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: set-matrix
      run: |
        $configs = (Get-ChildItem .github/workflows/config/framework/*.env | Select-Object -ExpandProperty "Name" | % {"\`"$_\`""}) -Join ","
        Write-Host "::set-output name=matrix::`"[$configs]`""
      shell: pwsh

  framework-desktop: 
    # SDKスタイルの方だけを対象にする。
    # 実際のプロダクトだと非SDKスタイルを今から採用するメリットがあまりないため、SDKスタイルで統一する前提
    needs: setup
    uses: ./.github/workflows/dotnet-sdk-style-framework-desktop.yml
    with:
      modules: ${{ fromJson(needs.setup.outputs.matrix) }}
      isPublish : false
    secrets: inherit
