name: 継続的インテグレーション

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        module: [constants]

    uses: ./.github/workflows/dotnet-sdk-style-framework-desktop.yml
    with:
      module: '${{ matrix.module }}'
