name: 継続的インテグレーション

on:
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - run: echo "HELLO MAIN"

  call-workflow:
    needs: [setup]
    uses: ./.github/workflows/dotnet-sdk-style-framework-desktop.yml
