# .NET で実装されたWPF用ワークフロー

name: .NET Desktop

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string
      version:
        required: true
        type: string
      isPublish:
        required: true
        type: boolean

jobs:
  build:
    strategy:
        matrix:
            modules: ${{ fromJson(inputs.modules) }}
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Load env from file
      uses: cardinalby/export-env-action@v2
      with:
        envFile: '.github/workflows/config/dotnet-desktop/${{ matrix.modules }}'
        expand: 'true'

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test $env:TestProject

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution /t:Restore

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:PackageProjectDirectory -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: >
        msbuild $env:Solution 
        /p:AppxBundle=Always
        /p:AppxBundlePlatforms='x64'
        /p:UapAppxPackageBuildMode='StoreUpload'
        /p:Configuration='Release'
        /p:Platform='x64'
        /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx 
        /p:PackageCertificatePassword='${{ secrets.Pfx_Key }}' 
        /p:Version=${{ inputs.version }}

    # Remove the pfx
    - name: Remove the pfx
      run: Remove-Item -path $env:PackageProjectDirectory\GitHubActionsWorkflow.pfx

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      if: inputs.isPublish
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PackageName }}
        path: ${{ env.PackageProjectDirectory }}\AppPackages
