name: manifests
on: [push]
jobs:
  list-manifests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/checkout@v2
    - id: set-matrix
      run: |
        $confs = (Get-ChildItem .github/workflows/config/*.env | Select-Object -ExpandProperty "Name" | % {"`"$_`""}) -Join ","
        Write-Host $confs
        Write-Host "::set-output name=matrix::[$confs]"
      shell:pwsh

  check:
    needs: list-manifests
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.list-manifests.outputs.matrix) }}
    steps:
    - run: echo ${{ matrix.manifest }}
