name: manifests
on: [push]
jobs:
  list-manifests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: Write-Host "::set-output name=matrix::$(ls .github/workflows/config/*.env | jq -R -s -c 'split("\n")[:-1]')"
        shell: pwsh
  check:
    needs: list-manifests
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.list-manifests.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.manifest }}
