name: manifests
on: [push]
jobs:
  list-manifests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/checkout@v2
    - id: set-matrix
      run: |
        echo "$(ls .github/workflows/config/*.env | jq -R -s -c 'split("\n")[:-1]')"
        echo "::set-output name=matrix::$(ls .github/workflows/config/*.env | jq -R -s -c 'split("\n")[:-1]')"

  check:
    needs: list-manifests
    runs-on: ubuntu-latest
    strategy:
        matrix:
            manifest: ${{ fromJson(needs.list-manifests.outputs.matrix) }}
    steps:
    - run: echo ${{ matrix.manifest }}
