name: モジュールリリース

on:
  push:
    tags:
      - 'release/**/*'

jobs:
  build:
    name: Create Release
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup config
        id: config
        run: |
          $source = $Env:GITHUB_REF
          Write-Host $source
          $tag = $source.Substring('refs/tags/'.Length)
          Write-Host $tag
          $temp = $tag.Substring($tag.IndexOf("/") + 1)
          $moduleType = $temp.Substring(0, $temp.IndexOf("/"))
          Write-Host $moduleType

          $temp = $temp.Substring($temp.IndexOf("/") + 1)
          $module = $temp.Substring(0, $temp.IndexOf("/"))
          Write-Host $module

          $version = $temp.Substring($temp.IndexOf("/") + 1)
          Write-Host $version
          Write-Host "::set-output name=moduleType::$moduleType"
          Write-Host "::set-output name=module::$module"
          Write-Host "::set-output name=version::$version"
        shell: pwsh
