name: モジュールリリース

on:
  push:
    tags:
      - 'release/**/*'

jobs:
  build:
    name: Create Release
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: |
          $source = $Env:GITHUB_REF
          Write-Host $source
          $tag = $source.Substring('refs/tags/'.Length)
          Write-Host $tag
          # $comment = (git tag -n | Where-Object { $_.StartsWith("$tag ") }).Substring($tag.Length + 1)
          # Write-Host $comment
          $moduleName = $tag.Substring(15, $tag.LastIndexOf('/') - 15)
          Write-Host $moduleName
          $version = $tag.Substring($tag.LastIndexOf('/') + 1)
          Write-Host $version
        shell: pwsh
