name: モジュールリリース

on:
  push:
    tags:
      - r*

jobs:
  setup:
    name: Setup release
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set version
        shell: pwsh
        run: |
          echo ("::debug:: GITHUB_REF: " + $GITHUB_REF + ".")
          Write-Host ("::debug:: GITHUB_REF: " + $GITHUB_REF)
          $tag = $GITHUB_REF.Substring('refs/tags/'.Length)
          echo "::debug:: tag: $tag"
          $moduleName = $tag.Substring(15, $tag.LastIndexOf('/') - 15)
          echo "::debug:: moduleName: $moduleName"
          $version = $tag.Substring($tag.LastIndexOf('/') + 1)
          echo "::debug:: version: $version"

