name: モジュールリリース

on:
  push:
    tags:
      - 'release/*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
          Write-Host "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"
        shell: pwsh