name: モジュールリリース

on:
  create:
    tags:
      - release/*

jobs:
  setup:
    name: Setup release
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set version
        shell: pwsh
        run: |
          Write-Host "::debug::debug $GITHUB_REF"