name: Test Reusing Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  parent:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: ./.github/workflows/test-child.yml
