name: Test Reusing Workflow child

on:
  workflow_call:

jobs:
  child:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: echo 'Hello, World!'
